name: Code quality check
on:
    push:
        branches:
            - main

jobs:
    code-quality-check:
        runs-on: ubuntu-latest
        env:
            USERNAME: CodeWithSophia
        steps:
            - name: Checkout-code
              uses: actions/checkout@v4
              
            - name: Run Super-Linter
              uses: github/super-linter@v4
              env:
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    test:
        runs-on: ubuntu-latest
        env:
            USERNAME: CodeWithSophia
        steps:
            - name: Print Github token and username
              run: |
                echo "GITHUB Token: ${{ secrets.GITHUB_TOKEN}}"
                echo "GITHUB Username: $USERNAME"

    build:
        runs-on: ubuntu-latest
        needs: test
        steps: 
          - name: checkout code
            uses: actions/checkout@v4
          - name: run a shell script
            run: |
              chmod +x even.sh
              ./even.sh
          - name: List files and folders
            run: ls -laR
          



